{
 "title": "kafka metricas",
 "tags": [ "kafka" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "volume dados",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_brokertopicmetrics_bytesinpersec_total{topic!~\"__consumer_offsets|all\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "quantidade",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_server_brokertopicmetrics_messagesinpersec_total{topic!~\"__consumer_offsets|all\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "média por segundo",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_brokertopicmetrics_messagesinpersec_total{topic!~\"__consumer_offsets|all\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}