server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: service-auto
  config:
    import: optional:file:/config/application.yml

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/db_auto
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

camel:
  routes:
    direct: 
      consultar-auto: direct:consultar-auto
      criar-auto: direct:criar-auto
    kafka:
      notificar-auto: kafka:notificar-auto?brokers={{camel.component.kafka.brokers}}

  component:
    kafka:
      autoCreateTopics: true
      brokers: host.docker.internal:9092
      group-id: service-auto
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  dataformat:
    jackson:
      auto-discover-object-mapper: true